services:
  backend:
    build: ./backend
    container_name: image-resizer-backend
    ports:
      - "5555:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: image-resizer-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped