name: Image Resizer CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker images
      run: |
        docker-compose build

    - name: Run containers
      run: |
        docker-compose up -d
        docker ps

    - name: Test backend
      run: |
        sleep 5
        curl -f http://localhost:3000 || (docker logs $(docker ps -q); exit 1)

      
